on:
  push:
    branches:
    - Develop
  pull_request:
    branches:
    - Develop
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      uses: greenygh0st/net-proj-release-version@v1
      with:  
      # Filepath of the *.csproj file, relative to root of repository
        PROJ_FILE: src/FakeAuth/FakeAuth.csproj

    - name: Echo Version
      run: echo "Version - ${{ steps.get_version.outputs.RELEASE_VERSION }}"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Package Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build