on:
  push:
    branches:
    - Develop
  pull_request:
    branches:
    - Develop
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    env:
      Nuget_Key: ${{ secrets.FAKEAUTH_NUGET_KEY }}
      Nuget_URL: "https://api.nuget.org/v3/index.json"
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Get version
      id: get_version
      uses: greenygh0st/net-proj-release-version@v1
      with:  
      # Filepath of the *.csproj file, relative to root of repository
        PROJ_FILE: src/FakeAuth/FakeAuth.csproj

    - name: Echo Project-sdk Version
      run: echo "${{ steps.get_version.outputs.RELEASE_VERSION }}"
    
    - name: Set Version variable with Preview suffix
      run: VERSION = ${{ steps.get_version.outputs.RELEASE_VERSION }}-preview"

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Package Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Pack
      run: echo dotnet pack --configuration Release /p:Version=${VERSION} --output .

    - name: Echo Push to Nuget
      run: echo dotnet nuget push FakeAuth.${VERSION}.nupkg --source ${env.Github_Key} --api-key ${env.Github_URL}
