on:
  push:
    branches:
    - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
      - '**.md'
  workflow_dispatch:

    env:
      Nuget_Key: secrets.FAKEAUTH_NUGET_KEY
      Nuget_URL: "https://api.nuget.org/v3/index.json"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Detect if workflow is running on origin/main
      id: detect_main
      run: git rev-parse HEAD | grep $(git rev-parse origin/main)
      continue-on-error: true
    
    - name: Verify commit exists in origin/main
      run: git log origin/main..HEAD | grep $(git rev-parse --short HEAD)
      if: ${{ steps.main_main.outcome == 'failure' }}

    - name: Get version
      id: get_version
      uses: greenygh0st/net-proj-release-version@v1
      with:  
      # Filepath of the *.csproj file, relative to root of repository
        PROJ_FILE: src/FakeAuth/FakeAuth.csproj
        
    - name: Set Release Version
      run: echo "getting version"
        
      env:
        RELEASE_VERSION: steps.get_version.outputs.RELEASE_VERSION

    - name: Show Release Version
      run: echo "Release Version is ${{steps.get_version.outputs.RELEASE_VERSION}}"
    
    - name: Generate build number
      uses: einaregilsson/build-number@v3
      with:
        token: ${{secrets.github_token}}        
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Package Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --configuration Release --no-build

    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${{steps.get_version.outputs.RELEASE_VERSION}} --include-symbols  --output .
      if: ${{ steps.main_main.outcome == 'success' }}
      
    - name: Push to Nuget
      run: dotnet nuget push FakeAuth.${{steps.get_version.outputs.RELEASE_VERSION}}.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{secrets.FAKEAUTH_NUGET_KEY}}
      if: ${{ steps.main_main.outcome == 'success' }}